// Generated by Apple Swift version 4.0.3 effective-3.2.3 (swiftlang-900.0.74.1 clang-900.0.39.2)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_attribute(external_source_symbol)
# define SWIFT_STRINGIFY(str) #str
# define SWIFT_MODULE_NAMESPACE_PUSH(module_name) _Pragma(SWIFT_STRINGIFY(clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in=module_name, generated_declaration))), apply_to=any(function, enum, objc_interface, objc_category, objc_protocol))))
# define SWIFT_MODULE_NAMESPACE_POP _Pragma("clang attribute pop")
#else
# define SWIFT_MODULE_NAMESPACE_PUSH(module_name)
# define SWIFT_MODULE_NAMESPACE_POP
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR __attribute__((enum_extensibility(open)))
# else
#  define SWIFT_ENUM_ATTR
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
@import AVFoundation;
@import UIKit;
@import Foundation;
@import ObjectiveC;
@import QuartzCore;
@import CoreGraphics;
@import MediaPlayer;
#endif

#import <LwayveSDK/LwayveSDK.h>

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

SWIFT_MODULE_NAMESPACE_PUSH("LwayveSDK")





///
SWIFT_PROTOCOL_NAMED("AnalyticsControlProtocol")
@protocol LwayveAnalyticsControlProtocol
/// Sends all pending analytic events.
- (void)sendAnalyticEvents;
/// The device Id used in analytics events
- (void)getAnalyticsDeviceId:(void (^ _Nonnull)(NSString * _Nonnull))completion;
@end

@class UIApplication;

/// The following methods are available for handling application remote notifications.
SWIFT_PROTOCOL_NAMED("ApplicationRemoteNotificationsHandler")
@protocol LwayveApplicationRemoteNotificationsHandler
/// This method should be called in -application:didFinishLaunchingWithOptions: of the application delegate after the SDK has been initialized.
/// \param application The singleton application object passed through <code>-application:didFinishLaunchingWithOptions</code>.
///
/// \param launchOptions A dictionary indicating the reason the app was launched (if any) passed through -application:didFinishLaunchingWithOptions:.
///
- (void)handleApplication:(UIApplication * _Nonnull)application didFinishLaunchingWithOptions:(NSDictionary<UIApplicationLaunchOptionsKey, id> * _Nullable)launchOptions;
/// This method should be called in <code>-application:didReceiveRemoteNotification:</code> or <code>-application:didReceiveRemoteNotification:fetchCompletionHandler</code> to handle remote notifications.
/// \param application The singleton app object.
///
/// \param userInfo A dictionary that contains information related to the remote notification.
///
- (void)handleApplication:(UIApplication * _Nonnull)application didReceiveRemoteNotification:(NSDictionary * _Nonnull)userInfo fetchCompletionHandler:(void (^ _Nonnull)(UIBackgroundFetchResult))fetchCompletionHandler;
/// This method should be called in <code>application(_ application:, didRegisterForRemoteNotificationsWithDeviceToken:)</code> to initialize remote notifications for the experience updates.
- (void)handleApplication:(UIApplication * _Nonnull)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData * _Nonnull)deviceToken;
/// Indicates the state of remote notifications listening. Set to <code>false</code> to stop receiving remote notifications.
@property (nonatomic) BOOL notificationsActive;
@end

@protocol LwayveAudioTrack;

/// The methods of the protocol allow the delegate to handle the sequence of audio track calling.
SWIFT_PROTOCOL_NAMED("AudioControlDelegate")
@protocol LwayveAudioControlDelegate
@optional
/// This method is called when the audio track has started loading before actual playing.
/// This method may be not called if the track was preloaded before.
/// In this case method <code>didStartPlayingTrack</code> will be called at once.
/// \param track The audio track that started playing.
///
- (void)lwayveSDKDidStartLoadingTrack:(id <LwayveAudioTrack> _Nonnull)track;
/// This method is called when the audio track has started playing.
/// \param track The audio track that started playing.
///
- (void)lwayveSDKDidStartPlayingTrack:(id <LwayveAudioTrack> _Nonnull)track;
/// This method is called when the audio track was paused.
/// \param track The audio track that was paused.
///
- (void)lwayveSDKDidPauseTrack:(id <LwayveAudioTrack> _Nonnull)track;
/// This method is called when the audio track was almost played to the end (about 0.1 sec left to the end).
/// \param track The audio track that was paused.
///
- (void)lwayveSDKDidAlmostPlayTrackToEnd:(id <LwayveAudioTrack> _Nonnull)track;
/// This method is called when the audio track was played to the end.
/// \param track The audio track that was paused.
///
- (void)lwayveSDKDidPlayTrackToEnd:(id <LwayveAudioTrack> _Nonnull)track;
/// This method is called when the audio track has ended.
/// \param track The audio track that ended.
///
- (void)lwayveSDKDidEndPlayingTrack:(id <LwayveAudioTrack> _Nonnull)track;
/// This method is called when the SDK has reached an error.
/// \param track The audio track that failed to play.
///
/// \param error The error object.
///
- (void)lwayveSDKDidFailPlayingTrack:(id <LwayveAudioTrack> _Nonnull)track withError:(NSError * _Nonnull)error;
/// This method is called when the audio player status has changed.
/// \param isReadyToPlay Set to <code>true</code> when the audio player has tracks to play. A host application should disable play controls when <code>isReadyToPlay == false</code>.
///
- (void)lwayveSDKPlayerIsReadyToPlayStatusDidChange:(BOOL)isReadyToPlay;
/// This method is called when the audio player status has changed.
/// \param canSkip Set to <code>true</code> when there is at least one unfinished track. A host application should disable the Skip button when <code>canSkip == false</code>.
///
- (void)lwayveSDKPlayerCanSkipStatusDidChange:(BOOL)canSkip;
/// This method is called when the audio player status has changed.
/// \param canRewind Set to <code>true</code> when the rewind action can be performed. A host application should disable the Rewind button when <code>canRewind == false</code>.
///
- (void)lwayveSDKPlayerCanRewindStatusDidChange:(BOOL)canRewind;
@end


/// The protocol that provides the additional interface for controlling the audio playback.
SWIFT_PROTOCOL_NAMED("AudioPlaybackControlProtocol")
@protocol LwayveAudioPlaybackControlProtocol
/// Determine if the audio player is ready to play an audio track. If <code>true</code> is returned, the audio player is ready.
/// seealso:
/// <code>AudioControlDelegate.lwayveSDK(playerIsReadyToPlayStatusDidChange:)</code>
@property (nonatomic, readonly) BOOL isReadyToPlay;
/// Determine if the skip action can be performed in the audio player.
/// seealso:
/// <code>AudioControlDelegate.lwayveSDK(playerCanSkipStatusDidChange:)</code>
@property (nonatomic, readonly) BOOL canSkip;
/// Determine if the rewind action can be performed in the audio player.
/// seealso:
/// <code>AudioControlDelegate.lwayveSDK(playerCanRewindStatusDidChange:)</code>
@property (nonatomic, readonly) BOOL canRewind;
/// Indicates if the audio player is currently playing an audio track.
/// seealso:
/// <code>AudioControlDelegate.lwayveSDK(didStartPlayingTrack:)</code>
/// seealso:
/// <code>AudioControlDelegate.lwayveSDK(didEndPlayingTrack:)</code>
@property (nonatomic, readonly) BOOL isPlaying;
/// Indicates if player is waiting for data to be loaded to continue playback.
/// seealso:
/// <code>AudioControlDelegate.lwayveSDK(didStartLoadingTrack:)</code>
@property (nonatomic, readonly) BOOL isWaitingForCurrentTrackToBeLoaded;
/// Start playing queued audio tracks.
/// seealso:
/// <code>isPlaying</code>
- (void)play;
/// Pause the playback of the current audio track.
/// seealso:
/// <code>AudioControlDelegate.lwayveSDK(didPauseTrack:)</code>
- (void)pause;
/// End the playback of the current audio track and remove all audio tracks from the queue.
- (void)stop;
/// End the playback of the current audio track and start the playback of the next audio track in the queue (if there is one).
- (void)skip;
/// Restart the current audio track from the beginning if it has played for greater than or equal to <code>kLwayveAudioPlaybackControlRewindThreshold</code> seconds;
/// otherwise, start playing the previous audio track (if any). If there is no previous audio track, start the current audio track from the beginning.
- (void)rewind;
@end

@class UIColor;

SWIFT_CLASS_NAMED("AudioRecordingScreenAppearance")
@interface LwayveAudioRecordingScreenAppearance : NSObject
@property (nonatomic, readonly, strong) UIColor * _Nonnull backgroundColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull statusTextColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull tryAgainButtonColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull sendButtonColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull playButtonColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull closeButtonColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull topTextColor;
/// If you pass <code>nil</code> to a parameter, then the default value will be applied.
- (nonnull instancetype)initWithBackgroundColor:(UIColor * _Nullable)backgroundColor statusTextColor:(UIColor * _Nullable)statusTextColor tryAgainButtonColor:(UIColor * _Nullable)tryAgainButtonColor sendButtonColor:(UIColor * _Nullable)sendButtonColor playButtonColor:(UIColor * _Nullable)playButtonColor closeButtonColor:(UIColor * _Nullable)closeButtonColor topTextColor:(UIColor * _Nullable)topTextColor OBJC_DESIGNATED_INITIALIZER;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull defaultBackgroundColor;)
+ (UIColor * _Nonnull)defaultBackgroundColor SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull defaultStatusTextColor;)
+ (UIColor * _Nonnull)defaultStatusTextColor SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull defaultTryAgainButtonColor;)
+ (UIColor * _Nonnull)defaultTryAgainButtonColor SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull defaultSendButtonColor;)
+ (UIColor * _Nonnull)defaultSendButtonColor SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull defaultPlayButtonColor;)
+ (UIColor * _Nonnull)defaultPlayButtonColor SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull defaultCloseButtonColor;)
+ (UIColor * _Nonnull)defaultCloseButtonColor SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull defaultTopTextColor;)
+ (UIColor * _Nonnull)defaultTopTextColor SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

enum LwayveLanguage : NSInteger;
@class LwayveClipActions;

/// The protocol representing the interface for the object that can be played in the audio player.
SWIFT_PROTOCOL_NAMED("AudioTrack")
@protocol LwayveAudioTrack <NSCoding>
/// The unique identifier of the audio track.
@property (nonatomic, readonly, copy) NSString * _Nonnull identifier;
/// The audio clip identifier.
@property (nonatomic, readonly, copy) NSString * _Nullable clipId;
/// An instance of the URL that references a media resource.
@property (nonatomic, readonly, copy) NSURL * _Nonnull url;
/// The name of the audio track.
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
/// The language of the audio track.
@property (nonatomic, readonly) enum LwayveLanguage language;
/// The duration of the audio track.
/// The initial value is kLwayveAudioTrackDurationIndefinite until the duration has been loaded.
/// To ensure that the value of the duration is loaded, use durationLoadHandler.
@property (nonatomic, readonly) NSTimeInterval duration;
/// Set your handler to receive updates about the loading of the audio track duration.
@property (nonatomic, copy) void (^ _Nullable durationLoadHandler)(NSTimeInterval);
@property (nonatomic, readonly, strong) LwayveClipActions * _Nonnull actions;
/// Segment ID from the experience containing the audio track
@property (nonatomic, readonly, copy) NSString * _Nullable segmentId;
/// Program ID from the experience containing the audio track
@property (nonatomic, readonly, copy) NSString * _Nullable programId;
/// Experience ID from the experience containing the audio track
@property (nonatomic, readonly, copy) NSString * _Nullable experienceId;
@end







@class UIImage;

/// <code>ClipAction</code> represents data required to display a clip related action.
SWIFT_CLASS_NAMED("ClipAction")
@interface LwayveClipAction : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable title;
@property (nonatomic, readonly, strong) UIImage * _Nullable image;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS_NAMED("ClipActions")
@interface LwayveClipActions : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end



@class NSCoder;

@interface LwayveClipActions (SWIFT_EXTENSION(LwayveSDK)) <NSCoding>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder;
@end


/// The following methods provide access to clip contextual actions
SWIFT_PROTOCOL_NAMED("ClipActionsProtocol")
@protocol LwayveClipActionsProtocol
/// Loads data required to display the requested clip related actions
/// \param actions actions object taken from <code>PlaylistItem.itemActions</code> or <code>AudioTrack.actions</code>
///
/// \param completion completion with actions data.
///
- (void)loadActions:(LwayveClipActions * _Nonnull)actions completion:(void (^ _Nonnull)(NSArray<LwayveClipAction *> * _Nonnull))completion;
/// Performs the clip related action
/// \param action action info object - result of method <code>loadActions(actions:completion:)</code>
///
/// \param completion the completion is called once the action finishes performing
///
- (void)performClipAction:(LwayveClipAction * _Nonnull)action completion:(void (^ _Nonnull)(void))completion;
@end

enum LwayveContentUpdateType : NSInteger;

SWIFT_CLASS("_TtC9LwayveSDK17ContentUpdateInfo")
@interface ContentUpdateInfo : NSObject
/// The content update type
@property (nonatomic, readonly) enum LwayveContentUpdateType type;
/// The item identifier
@property (nonatomic, readonly, copy) NSString * _Nullable itemIdentifier;
/// The situational text to display before playing
@property (nonatomic, readonly, copy) NSString * _Nullable situationalText;
- (BOOL)isNewContent SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, LwayveContentUpdateType, "ContentUpdateType") {
/// New contant available
  LwayveContentUpdateTypeNew = 0,
/// Situational content available
  LwayveContentUpdateTypeSituational = 1,
/// No new content available
  LwayveContentUpdateTypePlayed = 2,
};

@class LwayveUserContext;

/// The protocol provides an additional interface for updating Contextual Audio Experience context
/// and building an appropriate playlist.
SWIFT_PROTOCOL_NAMED("ContextControlProtocol")
@protocol LwayveContextControlProtocol
/// Update user likes in a Contextual Audio Experience.
/// \param userLikes The list of strings representing the updated user likes in the Contextual Audio Experience.
///
- (void)setUserLikes:(NSArray<NSString *> * _Nonnull)userLikes;
/// Add user likes to a Contextual Audio Experience.
/// \param userLikes The list of strings representing the user likes to add to the Contextual Audio Experience.
///
- (void)addUserLikes:(NSArray<NSString *> * _Nonnull)userLikes;
/// Remove user likes from a Contextual Audio Experience.
/// \param userLikes The list of strings representing the user likes to remove from the Contextual Audio Experience.
///
- (void)removeUserLikes:(NSArray<NSString *> * _Nonnull)userLikes;
/// Update locations in a Contextual Audio Experience.
/// \param locations The list of strings representing the updated locations in the Contextual Audio Experience.
///
- (void)setLocations:(NSArray<NSString *> * _Nonnull)locations;
/// Add locations to a Contextual Audio Experience.
/// \param locations The list of strings representing the locations to be added to the Contextual Audio Experience.
///
- (void)addLocations:(NSArray<NSString *> * _Nonnull)locations;
/// Remove locations from a Contextual Audio Experience.
/// \param locations The list of strings representing the locations to be removed from the Contextual Audio Experience.
///
- (void)removeLocations:(NSArray<NSString *> * _Nonnull)locations;
/// Set Exclusive Tag
/// \param exclusiveTag 
///
@property (nonatomic, copy) NSString * _Nullable exclusiveTag;
/// The data object that contains the user context that is being used for generating the playlist.
@property (nonatomic, readonly, strong) LwayveUserContext * _Nullable currentUserContext;
///
@property (nonatomic, readonly) NSTimeInterval timeOffset;
@end




/// The following methods provide additional control over a Contextual Audio Experience.
/// Usually, a host app does not have to use these methods until testing or debugging is needed.
SWIFT_PROTOCOL_NAMED("ExperienceControlProtocol")
@protocol LwayveExperienceControlProtocol
/// Request the Contextual Audio Experience, ignoring the local cache.
- (void)fetchExperienceFromServer;
@end


/// The following properties provide additional information about the current Contextual Audio Experience.
SWIFT_PROTOCOL_NAMED("ExperienceSupplementaryInfo")
@protocol LwayveExperienceSupplementaryInfo
/// All user likes present in the current Contextual Audio Experience.
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull allExperienceTags;
/// All locations present in the current Contextual Audio Experience.
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull allExperienceLocations;
/// Data object representing raw experience JSON.
@property (nonatomic, readonly, copy) NSData * _Nullable rawExperience;
@end




/// An object of the class represents a user location.
/// seealso:
/// <code>UserContext</code>
SWIFT_CLASS_NAMED("Location")
@interface LwayveLocation : NSObject
/// Location name.
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
///
@property (nonatomic, readonly) NSInteger hashValue;
///
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface LwayveLocation (SWIFT_EXTENSION(LwayveSDK)) <NSCoding>
///
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
///
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder;
@end

/// The enum of supported languages.
typedef SWIFT_ENUM(NSInteger, LwayveLanguage) {
  LwayveLanguageEnglish = 0,
  LwayveLanguageFrench = 1,
  LwayveLanguageSpanish = 2,
};


/// The following methods are available for controlling the information displayed in the iOS Control Center and on the iOS Lock screen for currently playing audio tracks.
SWIFT_PROTOCOL("_TtP9LwayveSDK28LwayveNowPlayingInfoProtocol_")
@protocol LwayveNowPlayingInfoProtocol
/// Get/set the default album artwork image that is displayed in the iOS Control Center and on the iOS Lock screen
/// if a track-specific image is not provided.
/// note:
/// The default image should be square.
@property (nonatomic, strong) UIImage * _Nullable defaultAlbumArtworkImage;
@end

@class LwayveSDK;
@class UIEvent;

/// LwayvePlaybackControlView provides a branded control for interaction
/// with the embeddable contextual audio experience service.
SWIFT_CLASS("_TtC9LwayveSDK25LwayvePlaybackControlView")
@interface LwayvePlaybackControlView : UIView
/// Set current using instance of LwayveSDK for controlling playback and handling its actual state.
@property (nonatomic, strong) LwayveSDK * _Nullable lwayveSDK;
/// Initializes and returns a newly allocated LwayvePlaybackControlView object
/// with the specified LwayveSDK branded interface.
/// \param frame The frame rectangle for the LwayvePlaybackControlView.
///
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSString * _Nonnull defaultTrackName;
@property (nonatomic, strong) UIColor * _Nonnull buttonsColor;
- (BOOL)pointInside:(CGPoint)point withEvent:(UIEvent * _Nullable)event SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)hitTest:(CGPoint)point withEvent:(UIEvent * _Nullable)event SWIFT_WARN_UNUSED_RESULT;
@end



@class LwayvePlaylist;

/// This protocol contains methods for handling playlist updates.
SWIFT_PROTOCOL_NAMED("PlayListEventsListener")
@protocol LwayvePlayListEventsListener
@optional
/// This method is called each time the playlist has been updated.
/// \param playlist The object that contains additional information about the updated playlist.
///
/// \param userContext UserContext of updated playlist
///
- (void)playlistDidUpdate:(LwayvePlaylist * _Nullable)playlist forUserContext:(LwayveUserContext * _Nonnull)userContext;
/// This method it called when last track of the playlist has finished playing
/// \param playlist The playlist that has been finished playing
///
- (void)playlistDidPlayToEnd:(LwayvePlaylist * _Nullable)playlist;
/// The method is called when new content update info changes
/// seealso:
/// <code>ContentUpdateType</code>
/// \param updateInfo indicates the type of update.
///
- (void)contentUpdateInfoDidChange:(ContentUpdateInfo * _Nonnull)updateInfo;
@end


@interface LwayvePlaybackControlView (SWIFT_EXTENSION(LwayveSDK)) <LwayvePlayListEventsListener>
- (void)contentUpdateInfoDidChange:(ContentUpdateInfo * _Nonnull)updateInfo;
@end


/// The following methods are available for handling generic LWAYVE SDK events.
SWIFT_PROTOCOL("_TtP9LwayveSDK17LwayveSDKDelegate_")
@protocol LwayveSDKDelegate
@optional
/// This method is called when the LWAYVE SDK has successfully initialized.
/// \param sdk The LWAYVE SDK object.
///
- (void)lwayveSDKDidInit:(LwayveSDK * _Nonnull)sdk;
/// This method is called when the LWAYVE SDK has been de-initialized.
/// \param sdk The LWAYVE SDK object.
///
- (void)lwayveSDKDidDeinit:(LwayveSDK * _Nonnull)sdk;
@end


@interface LwayvePlaybackControlView (SWIFT_EXTENSION(LwayveSDK)) <LwayveSDKDelegate>
- (void)lwayveSDKDidInit:(LwayveSDK * _Nonnull)sdk;
@end










@interface LwayvePlaybackControlView (SWIFT_EXTENSION(LwayveSDK))
@property (nonatomic, readonly) CGSize intrinsicContentSize;
@end




@interface LwayvePlaybackControlView (SWIFT_EXTENSION(LwayveSDK)) <LwayveAudioControlDelegate>
- (void)lwayveSDKDidStartLoadingTrack:(id <LwayveAudioTrack> _Nonnull)track;
- (void)lwayveSDKDidStartPlayingTrack:(id <LwayveAudioTrack> _Nonnull)track;
- (void)lwayveSDKDidPauseTrack:(id <LwayveAudioTrack> _Nonnull)track;
- (void)lwayveSDKDidAlmostPlayTrackToEnd:(id <LwayveAudioTrack> _Nonnull)track;
- (void)lwayveSDKDidEndPlayingTrack:(id <LwayveAudioTrack> _Nonnull)track;
- (void)lwayveSDKDidFailPlayingTrack:(id <LwayveAudioTrack> _Nonnull)track withError:(NSError * _Nonnull)error;
- (void)lwayveSDKPlayerIsReadyToPlayStatusDidChange:(BOOL)isReadyToPlay;
- (void)lwayveSDKPlayerCanSkipStatusDidChange:(BOOL)canSkip;
- (void)lwayveSDKPlayerCanRewindStatusDidChange:(BOOL)canRewind;
@end

@class UIFont;

@interface LwayvePlaybackControlView (SWIFT_EXTENSION(LwayveSDK))
@property (nonatomic, strong) UIFont * _Nonnull trackNameFont;
@property (nonatomic, strong) UIColor * _Nonnull trackNameTextColor;
@property (nonatomic, strong) UIColor * _Nullable trackNameBackgroundColor;
@property (nonatomic, strong) UIColor * _Nullable outerBandColor;
@property (nonatomic, strong) UIImage * _Nullable backgroundImage;
@end

@class LwayveSDKConfiguration;

/// Use singleton instance of <code>LwayveSDK</code> available by <code>LwayveSDK.sharedSDK</code> to communicate with the SDK.
SWIFT_CLASS("_TtC9LwayveSDK9LwayveSDK")
@interface LwayveSDK : NSObject
@property (nonatomic, readonly, strong) LwayveSDKConfiguration * _Nullable configuration;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
/// This method must be called before the SDK can be used.
/// seealso:
/// <code>LwayveSDKDelegate.lwayveSDK(didInit:)</code>
/// seealso:
/// <code>LwayveSDKInitializationError</code>
/// \param configuration Configuration object with required parameters
///
- (BOOL)initializeWithConfiguration:(LwayveSDKConfiguration * _Nonnull)configuration error:(NSError * _Nullable * _Nullable)error;
/// The SDK will be deinitialized after calling this method.
/// note:
/// Deinitialization may be asynchronious. Wait for <code>LwayveSDKDelegate.lwayveSDK(didDeinit:)</code> to be called before initializing the SDK again.
- (void)deinitialize;
/// The singleton object of <code>LwayveSDK</code>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LwayveSDK * _Nonnull sharedSDK;)
+ (LwayveSDK * _Nonnull)sharedSDK SWIFT_WARN_UNUSED_RESULT;
/// Adds the listener for the playlist events
- (void)addPlaylistEventsListener:(id <LwayvePlayListEventsListener> _Nonnull)playlistEventsListener;
/// Removes the listener for the playlist events
- (void)removePlaylistEventsListener:(id <LwayvePlayListEventsListener> _Nonnull)playlistEventsListener;
/// Add delegate
/// \param delegate Receiver of lwayve states notifications
///
- (void)addDelegate:(id <LwayveSDKDelegate> _Nonnull)delegate;
/// Remove delegate
/// \param delegate Receiver of lwayve states notifications
///
- (void)removeDelegate:(id <LwayveSDKDelegate> _Nonnull)delegate;
/// Using this property you can get or update the SDK preferred language.
/// Update is an asynchronous operation. The default value is the current device language, if the LWAYVE SDK supports it.
/// If a language is not set on the current device, the default is LwayveLanguage.english.
@property (nonatomic) enum LwayveLanguage language;
/// Adds a listener for audio playback events.
/// \param delegate An object conforming to the <code>AudioControlDelegate</code> protocol.
///
- (void)addAudioControlDelegate:(id <LwayveAudioControlDelegate> _Nonnull)delegate;
/// Removes a listener for audio playback events.
/// \param delegate An object conforming to the <code>AudioControlDelegate</code> protocol.
///
- (void)removeAudioControlDelegate:(id <LwayveAudioControlDelegate> _Nonnull)delegate;
@end


@interface LwayveSDK (SWIFT_EXTENSION(LwayveSDK))
- (void (^ _Nonnull)(void))getProxSeeConfigurationKey:(void (^ _Nonnull)(NSString * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
@end

@protocol LXTagsProxyProtocol;

@interface LwayveSDK (SWIFT_EXTENSION(LwayveSDK)) <LXTagsReceiverProxyProtocol>
- (void)didChangeTagsSet:(id <LXTagsProxyProtocol> _Nonnull)tags;
@end


SWIFT_PROTOCOL("_TtP9LwayveSDK27OuterBandAppearanceProtocol_")
@protocol OuterBandAppearanceProtocol
/// \param actionType Use value from <code>PredefinedClipActionTypes</code>
///
- (void)overrideImage:(UIImage * _Nullable)image forActionType:(NSString * _Nonnull)actionType;
/// \param title The title should be localized
///
/// \param actionType Use value from <code>PredefinedClipActionTypes</code>
///
- (void)overrideTitle:(NSString * _Nullable)title forActionType:(NSString * _Nonnull)actionType;
@end


@interface LwayveSDK (SWIFT_EXTENSION(LwayveSDK)) <OuterBandAppearanceProtocol>
/// See <code>OuterBandAppearanceProtocol.overrideImage(_:forActionType:)</code>
- (void)overrideImage:(UIImage * _Nullable)image forActionType:(NSString * _Nonnull)actionType;
/// See <code>OuterBandAppearanceProtocol.overrideTitle(_:forActionType:)</code>
- (void)overrideTitle:(NSString * _Nullable)title forActionType:(NSString * _Nonnull)actionType;
@end


@interface LwayveSDK (SWIFT_EXTENSION(LwayveSDK)) <LwayveAnalyticsControlProtocol>
- (void)sendAnalyticEvents;
- (void)getAnalyticsDeviceId:(void (^ _Nonnull)(NSString * _Nonnull))completion;
@end


@interface LwayveSDK (SWIFT_EXTENSION(LwayveSDK)) <LwayveSDKDelegate>
- (void)lwayveSDKDidInit:(LwayveSDK * _Nonnull)sdk;
- (void)lwayveSDKDidDeinit:(LwayveSDK * _Nonnull)sdk;
@end


@interface LwayveSDK (SWIFT_EXTENSION(LwayveSDK)) <LwayveClipActionsProtocol>
/// See <code>ClipActionsProtocol.loadActions(actions:completion:)</code>
- (void)loadActions:(LwayveClipActions * _Nonnull)actions completion:(void (^ _Nonnull)(NSArray<LwayveClipAction *> * _Nonnull))completion;
/// See <code>ClipActionsProtocol.performClipAction(_:completion:)</code>
- (void)performClipAction:(LwayveClipAction * _Nonnull)actionInfo completion:(void (^ _Nonnull)(void))completion;
@end


@interface LwayveSDK (SWIFT_EXTENSION(LwayveSDK)) <LwayveNowPlayingInfoProtocol>
/// See <code>LwayveNowPlayingInfoProtocol.defaultAlbumArtworkImage</code>
@property (nonatomic, strong) UIImage * _Nullable defaultAlbumArtworkImage;
@end

enum LwayveUserRecordedAudioDuration : NSInteger;

SWIFT_PROTOCOL("_TtP9LwayveSDK31UserRecordedAudioUploadProtocol_")
@protocol UserRecordedAudioUploadProtocol
/// The file at <code>fileURL</code> will be validated and uploaded to Lwayve server to be reviewed and added to the experience.
/// \param fileURL The <code>fileURL</code> must be a URL to the local file system accessible to the application. The audio file requirements:
/// <ul>
///   <li>
///     Supported formats: .mp3, .m4a;
///   </li>
///   <li>
///     The file must contain non-empty audio;
///   </li>
///   <li>
///     The audio file size must be not more than 2MB;
///   </li>
///   <li>
///     the length of the audio in the file must be not more than 1 minute.
///   </li>
/// </ul>
///
/// \param completion <code>error == nil</code> indicates a successful finish of the upload. <code>error</code> can be of following types: <code>UserRecordedAudioUploaderError</code>, <code>UserRecordedAudioValidatorError</code>
///
- (void)uploadUserRecordedAudioWithFileURL:(NSURL * _Nonnull)fileURL completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
/// Maximum audio duration that can be recored using record action from the outer band.
@property (nonatomic) enum LwayveUserRecordedAudioDuration maximumUserRecordedAudioDuration;
@end


@interface LwayveSDK (SWIFT_EXTENSION(LwayveSDK)) <UserRecordedAudioUploadProtocol>
/// See <code>UserRecordedAudioUploadProtocol.uploadUserRecordedAudio(fileURL:completion:)</code>
- (void)uploadUserRecordedAudioWithFileURL:(NSURL * _Nonnull)fileURL completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
/// See <code>UserRecordedAudioUploadProtocol.maximumUserRecordedAudioDuration</code>
@property (nonatomic) enum LwayveUserRecordedAudioDuration maximumUserRecordedAudioDuration;
@end


@interface LwayveSDK (SWIFT_EXTENSION(LwayveSDK))
@property (nonatomic, copy) void (^ _Nullable analyticsEventTrackHandler)(NSString * _Nonnull);
@end


@interface LwayveSDK (SWIFT_EXTENSION(LwayveSDK))
/// Intitializes Lwayve with ProxSee integration.
/// This method must be called before the SDK can be used.
/// seealso:
/// <code>LwayveSDKDelegate.lwayveSDK(didInit:)</code>
/// seealso:
/// <code>LwayveSDKInitializationError</code>
/// \param configuration Configuration object with required parameters
///
- (BOOL)initializeWithProxSeeWithConfiguration:(LwayveSDKConfiguration * _Nonnull)configuration error:(NSError * _Nullable * _Nullable)error;
@end


@interface LwayveSDK (SWIFT_EXTENSION(LwayveSDK)) <LwayveApplicationRemoteNotificationsHandler>
/// See <code>ApplicationRemoteNotificationsHandler.notificationsActive</code>
@property (nonatomic) BOOL notificationsActive;
/// See <code>ApplicationRemoteNotificationsHandler.handleApplication(_:didFinishLaunchingWithOptions:)</code>
- (void)handleApplication:(UIApplication * _Nonnull)application didFinishLaunchingWithOptions:(NSDictionary<UIApplicationLaunchOptionsKey, id> * _Nullable)launchOptions;
/// See <code>ApplicationRemoteNotificationsHandler.handleApplication(_:didReceiveRemoteNotification:fetchCompletionHandler:)</code>
- (void)handleApplication:(UIApplication * _Nonnull)application didReceiveRemoteNotification:(NSDictionary * _Nonnull)userInfo fetchCompletionHandler:(void (^ _Nonnull)(UIBackgroundFetchResult))fetchCompletionHandler;
- (void)handleApplication:(UIApplication * _Nonnull)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData * _Nonnull)deviceToken;
@end


@interface LwayveSDK (SWIFT_EXTENSION(LwayveSDK)) <LwayveExperienceSupplementaryInfo>
/// See <code>ExperienceSupplementaryInfo.allExperienceTags</code>
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull allExperienceTags;
/// See <code>ExperienceSupplementaryInfo.allExperienceLocations</code>
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull allExperienceLocations;
@property (nonatomic, readonly, copy) NSData * _Nullable rawExperience;
@end


@interface LwayveSDK (SWIFT_EXTENSION(LwayveSDK))
@property (nonatomic) NSInteger audioBufferMaxTrackCount;
@property (nonatomic) NSInteger audioBufferMaxSize;
@property (nonatomic) NSInteger audioCacheMaxSize;
- (void)clearAudioCache;
@end


@interface LwayveSDK (SWIFT_EXTENSION(LwayveSDK)) <LwayveAudioPlaybackControlProtocol>
/// See <code>AudioPlaybackControlProtocol.isReadyToPlay</code>
@property (nonatomic, readonly) BOOL isReadyToPlay;
/// See <code>AudioPlaybackControlProtocol.canSkip</code>
@property (nonatomic, readonly) BOOL canSkip;
/// See <code>AudioPlaybackControlProtocol.canRewind</code>
@property (nonatomic, readonly) BOOL canRewind;
/// See <code>AudioPlaybackControlProtocol.isPlaying</code>
@property (nonatomic, readonly) BOOL isPlaying;
@property (nonatomic, readonly) BOOL isWaitingForCurrentTrackToBeLoaded;
/// See <code>AudioPlaybackControlProtocol.play()</code>
- (void)play;
/// See <code>AudioPlaybackControlProtocol.pause()</code>
- (void)pause;
/// See <code>AudioPlaybackControlProtocol.stop()</code>
- (void)stop;
/// See <code>AudioPlaybackControlProtocol.skip()</code>
- (void)skip;
/// See <code>AudioPlaybackControlProtocol.rewind()</code>
- (void)rewind;
@end


@interface LwayveSDK (SWIFT_EXTENSION(LwayveSDK)) <LwayveContextControlProtocol>
/// See <code>ContextControlProtocol.set(locations:)</code>
- (void)setLocations:(NSArray<NSString *> * _Nonnull)locations;
/// See <code>ContextControlProtocol.set(userLikes:)</code>
- (void)setUserLikes:(NSArray<NSString *> * _Nonnull)userLikes;
/// See <code>ContextControlProtocol.currentUserContext</code>
@property (nonatomic, readonly, strong) LwayveUserContext * _Nullable currentUserContext;
/// See <code>ContextControlProtocol.add(userLikes:)</code>
- (void)addUserLikes:(NSArray<NSString *> * _Nonnull)userLikes;
/// See <code>ContextControlProtocol.add(locations:)</code>
- (void)addLocations:(NSArray<NSString *> * _Nonnull)locations;
/// See <code>ContextControlProtocol.remove(userLikes:)</code>
- (void)removeUserLikes:(NSArray<NSString *> * _Nonnull)userLikes;
/// See <code>ContextControlProtocol.remove(locations:)</code>
- (void)removeLocations:(NSArray<NSString *> * _Nonnull)locations;
@property (nonatomic) NSTimeInterval timeOffset;
@property (nonatomic, copy) NSString * _Nullable exclusiveTag;
@end


/// This protocol provides an interface for controlling the Contextual Audio Experience playlist.
SWIFT_PROTOCOL_NAMED("PlaylistControlProtocol")
@protocol LwayvePlaylistControlProtocol
/// Refresh the playlist based on the current context of playlist builder.
- (void)refreshPlaylist;
/// Re-request the Contextual Audio Experience from the server.
- (void)forceReloadExperience;
/// The list of items in the playlist.
@property (nonatomic, readonly, strong) LwayvePlaylist * _Nullable generatedPlaylist;
/// The list of audio tracks in the queue, including the currently playing audio track (if any).
@property (nonatomic, readonly, copy) NSArray<id <LwayveAudioTrack>> * _Nonnull audioQueue;
/// The list of unplayed audio tracks.
@property (nonatomic, readonly, copy) NSArray<id <LwayveAudioTrack>> * _Nonnull unplayedTracksQueue;
/// The list of played audio tracks. The last audio track in the list is the most recently played one.
@property (nonatomic, readonly, copy) NSArray<id <LwayveAudioTrack>> * _Nonnull playedTracksHistory;
/// The list of identifiers for the played audio tracks.
@property (nonatomic, readonly, copy) NSSet<NSString *> * _Nonnull playedTracksIds;
/// Clear the history of played audio tracks.
- (void)clearPlayedItems;
/// Indicates if current playlist contains new content.
@property (nonatomic, readonly, strong) ContentUpdateInfo * _Nonnull contentUpdateInfo;
@end


@interface LwayveSDK (SWIFT_EXTENSION(LwayveSDK)) <LwayvePlaylistControlProtocol>
/// See <code>PlayListEventsListener.playlist</code>
@property (nonatomic, readonly, strong) LwayvePlaylist * _Nullable playlist;
/// See <code>PlaylistControlProtocol.refreshPlaylist()</code>
- (void)refreshPlaylist;
/// See <code>PlaylistControlProtocol.forceReloadExperience()</code>
- (void)forceReloadExperience;
/// See <code>PlaylistControlProtocol.generatedPlaylist</code>
@property (nonatomic, readonly, strong) LwayvePlaylist * _Nullable generatedPlaylist;
/// See <code>PlaylistControlProtocol.audioQueue</code>
@property (nonatomic, readonly, copy) NSArray<id <LwayveAudioTrack>> * _Nonnull audioQueue;
/// See <code>PlaylistControlProtocol.unplayedTracksQueue</code>
@property (nonatomic, readonly, copy) NSArray<id <LwayveAudioTrack>> * _Nonnull unplayedTracksQueue;
/// See <code>PlaylistControlProtocol.playedTracksHistory</code>
@property (nonatomic, readonly, copy) NSArray<id <LwayveAudioTrack>> * _Nonnull playedTracksHistory;
/// See <code>PlaylistControlProtocol.playedTracksIds</code>
@property (nonatomic, readonly, copy) NSSet<NSString *> * _Nonnull playedTracksIds;
/// See <code>PlaylistControlProtocol.clearPlayedItems()</code>
- (void)clearPlayedItems;
/// See <code>PlaylistControlProtocol.var contentUpdateInfo: ContentUpdateType</code>
@property (nonatomic, readonly, strong) ContentUpdateInfo * _Nonnull contentUpdateInfo;
@end

enum LwayveSDKConfigurationType : NSInteger;

/// A <code>LwayveSDKConfiguration</code> object defines parameters required for LWAYVE SDK.
SWIFT_CLASS("_TtC9LwayveSDK22LwayveSDKConfiguration")
@interface LwayveSDKConfiguration : NSObject
/// Use configurationType to set predefined deployment settings.
@property (nonatomic, readonly) enum LwayveSDKConfigurationType configurationType;
/// Use baseURL to override the default LWAYVE service URL.
@property (nonatomic, readonly, copy) NSURL * _Nonnull baseURL;
/// Authentification token
@property (nonatomic, readonly, copy) NSString * _Nonnull authenticationToken;
/// Enables the user audio recording UI
@property (nonatomic, readonly) BOOL userAudioRecordingEnabled;
/// Audio recording screen appearance.
@property (nonatomic, readonly, strong) LwayveAudioRecordingScreenAppearance * _Nonnull audioRecordingScreenAppearance;
/// The event name is used for user messages presented by SDK where the app or event name is important (e.g. microphone permissions request, etc)
@property (nonatomic, readonly, copy) NSString * _Nonnull localizedEventName;
/// Default initializer
/// \param configurationType - see <code>LwayveSDKConfiguration.configurationType</code>
///
/// \param baseURL - see <code>baseURL</code>. Use <code>baseURL = nil</code> to use default URL for configurationType.
///
/// \param authenticationToken - see <code>LwayveSDKConfiguration.authenticationToken</code>
///
/// \param userAudioRecordingEnabled - see <code>LwayveSDKConfiguration.userAudioRecordingEnabled</code>. Default value <code>false</code>.
///
/// \param audioRecordingScreenAppearance - see <code>LwayveSDKConfiguration.audioRecordingScreenAppearance</code>.
/// You can pass <code>nil</code> to use the default value in Objective-C
///
/// \param localizedEventName see <code>LwayveSDKConfiguration.localizedEventName</code>. Default value <code>LWAYVE</code>.
/// You can pass <code>nil</code> to use the default value in Objective-C
///
- (nonnull instancetype)initWithConfigurationType:(enum LwayveSDKConfigurationType)configurationType baseURL:(NSURL * _Nullable)baseURL authenticationToken:(NSString * _Nonnull)authenticationToken userAudioRecordingEnabled:(BOOL)userAudioRecordingEnabled audioRecordingScreenAppearance:(LwayveAudioRecordingScreenAppearance * _Nullable)audioRecordingScreenAppearance localizedEventName:(NSString * _Nullable)localizedEventName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

typedef SWIFT_ENUM(NSInteger, LwayveSDKConfigurationType) {
  LwayveSDKConfigurationTypeQa = 0,
  LwayveSDKConfigurationTypeProd = 1,
};


/// The error can be thrown by the <code>LwayveSDK.initialize(configuration:)</code> method.
typedef SWIFT_ENUM(NSInteger, LwayveSDKInitializationError) {
  LwayveSDKInitializationErrorUnknownError = 0,
  LwayveSDKInitializationErrorAlreadyInitialized = 1,
};
static NSString * _Nonnull const LwayveSDKInitializationErrorDomain = @"LwayveSDK.LwayveSDKInitializationError";





@protocol LwayvePlaylistItem;

/// Contains information about the generated playlist.
SWIFT_CLASS_NAMED("Playlist")
@interface LwayvePlaylist : NSObject
/// The unique identifier of the playlist.
@property (nonatomic, readonly, copy) NSString * _Nonnull identifier;
/// The value representing the date the playlist will be updated.
@property (nonatomic, readonly, copy) NSDate * _Nullable nextEventTime;
/// The playlist items.
@property (nonatomic, readonly, copy) NSArray<id <LwayvePlaylistItem>> * _Nonnull items;
/// If <code>shouldAutoRestart == false</code>, then the user should press play button to play a new playlist. This is the default behaviour.
/// If <code>shouldAutoRestart == true</code>, then a new playlist should start playing automaticaly.
@property (nonatomic, readonly) BOOL shouldAutoRestart;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@protocol LwayvePlaylistItemMetadata;

/// This protocol contains information about the objects that will be used for preparing the playlist.
SWIFT_PROTOCOL_NAMED("PlaylistItem")
@protocol LwayvePlaylistItem
/// The unique identifier of the playlist item.
@property (nonatomic, readonly, copy) NSString * _Nonnull identifier;
/// The audio clip identifier.
@property (nonatomic, readonly, copy) NSString * _Nullable clipId;
/// The name of the playlist item.
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
/// The string representing the path for the playlist item resource.
@property (nonatomic, readonly, copy) NSString * _Nullable url;
/// The language of the audio track.
@property (nonatomic, readonly) enum LwayveLanguage language;
/// Indicates if the item represents situational content.
@property (nonatomic, readonly) BOOL isSituational;
@property (nonatomic, readonly, strong) id <LwayvePlaylistItemMetadata> _Nonnull itemMetadata;
@property (nonatomic, readonly, strong) LwayveClipActions * _Nonnull itemActions;
@end


/// This protocol contains information about the objects that will be used for preparing the playlist.
SWIFT_PROTOCOL_NAMED("PlaylistItemMetadata")
@protocol LwayvePlaylistItemMetadata
/// The text to display before playing situational audio.
@property (nonatomic, readonly, copy) NSString * _Nullable situationalText;
@end


/// The class contains constants that can be used in methods of <code>OuterBandAppearanceProtocol</code> protocol
SWIFT_CLASS("_TtC9LwayveSDK25PredefinedClipActionTypes")
@interface PredefinedClipActionTypes : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull url;)
+ (NSString * _Nonnull)url SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull map;)
+ (NSString * _Nonnull)map SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ticket;)
+ (NSString * _Nonnull)ticket SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull hotel;)
+ (NSString * _Nonnull)hotel SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull share;)
+ (NSString * _Nonnull)share SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull record;)
+ (NSString * _Nonnull)record SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// An object of the class represents a user like.
/// seealso:
/// <code>UserContext</code>
SWIFT_CLASS_NAMED("Tag")
@interface LwayveTag : NSObject
/// The name of the user like.
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
///
@property (nonatomic, readonly) NSInteger hashValue;
///
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface LwayveTag (SWIFT_EXTENSION(LwayveSDK)) <NSCoding>
///
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
///
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder;
@end










/// An object of the class represents context which is used to generate a user specific Contextual Audio Experience playlist.
SWIFT_CLASS_NAMED("UserContext")
@interface LwayveUserContext : NSObject
/// The user’s date/time in the UTC time zone.
@property (nonatomic, readonly, copy) NSDate * _Nonnull time;
/// The time offset which will be applied to actual time to simulate different user time without changin actual OS time.
@property (nonatomic, readonly) NSTimeInterval timeOffset;
/// The list of locations.
@property (nonatomic, readonly, copy) NSSet<LwayveLocation *> * _Nonnull locations;
/// The list of user likes.
@property (nonatomic, readonly, copy) NSSet<LwayveTag *> * _Nonnull tags;
/// If the experience contains nodes marked with the tag, the clips with the tag will be played before other clips
@property (nonatomic, readonly, strong) LwayveTag * _Nullable exclusiveTag;
/// The list of identifiers for the played audio tracks.
@property (nonatomic, readonly, copy) NSSet<NSString *> * _Nonnull playedPlaylistItemIds;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end






@interface LwayveUserContext (SWIFT_EXTENSION(LwayveSDK)) <NSCoding>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, LwayveUserRecordedAudioDuration, "UserRecordedAudioDuration") {
  LwayveUserRecordedAudioDurationShort = 0,
  LwayveUserRecordedAudioDurationLong = 1,
};


typedef SWIFT_ENUM_NAMED(NSInteger, LwayveUserRecordedAudioUploaderError, "UserRecordedAudioUploaderError") {
  LwayveUserRecordedAudioUploaderErrorWaitUntilPreviousUploadFinishes = 0,
  LwayveUserRecordedAudioUploaderErrorUnknownUploadError = 1,
};
static NSString * _Nonnull const LwayveUserRecordedAudioUploaderErrorDomain = @"LwayveSDK.UserRecordedAudioUploaderError";

typedef SWIFT_ENUM_NAMED(NSInteger, LwayveUserRecordedAudioValidator, "UserRecordedAudioValidatorError") {
  LwayveUserRecordedAudioValidatorNotFileURL = 0,
  LwayveUserRecordedAudioValidatorFileNotFound = 1,
  LwayveUserRecordedAudioValidatorFileSizeIsTooBig = 2,
  LwayveUserRecordedAudioValidatorAudioIsTooLong = 3,
/// Supported formats: .mp3, .m4a. The file must contain non-empty audio.
  LwayveUserRecordedAudioValidatorUnsupportedFormat = 4,
};
static NSString * _Nonnull const LwayveUserRecordedAudioValidatorDomain = @"LwayveSDK.UserRecordedAudioValidatorError";

SWIFT_MODULE_NAMESPACE_POP
#pragma clang diagnostic pop
